[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/109_ONvn6OUlDksO7B6-Wrq6klmDkbIUH5AscqLJmhX8/edit#gid=0"

# From your JSON key file
type = "service_account"
project_id = "sonorous-path-410305"
private_key_id = "9aa48fb850e6333b0989bab202a9fc0c327039d5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4mLL2aGU+M0cY
g+9ExfEQmDyiKcAJNpcWDTY3d69BTpGzA0Zg3D+G2/Fx7n4OI0IPvrEVDo6Pnzxc
ageRiFdXZ9RpSgMYL9v+0K9HkmK6bQYGjW6Ai5okMD3bI2UwPc0syWvs4C5kKZQk
7YuyktjVoLgM/A/Nbt5zAYmyRgPTz8M9w3WzxT/ff0+c3HLm3Y2R1X1o4IusQeWt
E+S2Ou7sZOdpIhMFmdQji1X0jzHnhrhZ43NOIuU//unrM/2/wzgDtyGpiPL5kjpS
B/qY3NOXF8nciS6cgAefaP7IiqGn74QMPz5ZbXeKuJ5iKzC8lHrR8nsB0el4y6D7
3w/Cd5m7AgMBAAECggEADfX6fvlJQumE5H1B8M0ZnLwuxcLrk6bNyWypX4uNNR64
lTXXskamBVCIE6pKXU5cVi2BXgrSTFlqKsEYHnEVzfX70hS3ZDJmbICi6QJQtjG9
pWw34b/tIfSGERc9tWbPKCZ5o5oW2Btu6VYP3SsO/CUiFlVP6qUKbN8+Zz21V2T7
k2u3ZYGPMrWr8DhzyTZFbO0XQgMH8R7qdqWdxNUc2il5GrzZ0j1I6Zpclp3eK4+d
v+mpzgo4c9AIDOIy9Hxf4/Q8KyLXEn6SRPshPJ+MtHusajyqFxaZBdYO0iOLaMsA
05PU0eGF1qF54zxyTVvKVbeSbQpuEHfczJ+dEKfRIQKBgQDzTjrechggFVQqLMfy
e9agcZTGK66mVVR6a5mBmpVLKasyP3CyjgHQR1Gkm6aeSChT/E5QYguDxKgONyy3
NeO+hazBkZ6EX/0csubAlf8Dx1t1j/HFYE9/h+nlzI5vQb8X4TkffM8SxtH92bT0
NCsyvih3/ouL/7BGsvkxkSF+oQKBgQDCOk6FRWW1WjMRF/I0xOTbPsA6gCSzq741
BU1uRFO221HNHgW+NMEK6os8uWRJsK6qOEU5QAUsvwAym49AM7RuZYbEOOtTO/yH
p67WfuM3zkUaHu3oJny1auFTmJ5mL6BJ8jowOxfwZC2reMTe4Hf3PuUyoK8G8Jn1
DYFzrYiG2wKBgCUGUZUKPbucI0urtt2ilL2jqyUg/pnXQFzExP5g/LkMZT3nQ4oY
bBQ61iS7fvZ1OpXVPkGjOedaZMyM/uP+cmLKyshGFZ5FUSot20mRSdZUXwmb1wnX
JyHcF+7dWwt5MNA8eMne31AXK1t65ruGuNAm+deQx8GNLlED6UHuuO8hAoGAXQXH
7ZRbLgxRQPKTEirq4Qag0mPlMBglNQehGhqnbYCFIRQr8/kYK75BiYfRPGnefbAN
l2nOEKw50AMpDLq2w9jkPr50Fp04SVBKMHj9IhEsj2IY14L3X3wdBwildJOC1Wep
7seeo4eXR/TDdWtUiZoZ87F5on1Bf1hEk76dENkCgYEAjmbNy9087VnZh7ZJ8sIH
BmlVDJqvOabWyOiqGCjZaM0T+mIhXDckmEEH1tie8Rzc3UMZzOrDXcl/Dh9Gcx5b
qAA95kbPrZRbxRWTASvCfcgQLtRu1Zs7C4tcJ9LWO1pbB5YX/7PKNeZiCJDHNH4y
QIblxpIf7NAvdXXDzCnRfRY=
-----END PRIVATE KEY-----
"""
client_email = "service-acc@sonorous-path-410305.iam.gserviceaccount.com"
client_id = "112166125505275731949"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-acc%40sonorous-path-410305.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
